### ISSUE TITLE
setuptools-compatible packaging?

### ISSUE THREAD

**Issue by vikanezrimaya** [martymcguire/spano#3]
I use NixOS for deployment and configuration of my server (and my IndieWeb site!), and while I probably could try to adapt Spano as a package with a custom buildPhase, a setup.py specifying all dependencies would simplify the deployment a lot.

The thing is: NixOS has a weird packaging setup which doesn't allow you to install and run programs outside of its package store, but it integrates well with existing build systems allowing for packaging a lot of programs with just specifying name, version and source repo. For example, I'd package Flask-Indieauth like this:

```nix
{ python3, lib, fetchPypi }:
python3.buildPythonPackage rec {
  # name and version
  pname = "Flask-IndieAuth";
  version = "0.0.3.2";
  # where to fetch the sources from; in this case, PyPI
  src = fetchPypi {
    # the package has the exact name and version as we specified earlier, DRY
    inherit pname version;
    sha256 = "<...>"; # Nix needs hashes of all build inputs for reproducibility and security!
  };
}
```
I see you already have a setup.py for Flask-Indieauth, which maybe could be reused here?

**Comment by martymcguire** [comment]
Thanks for taking a look at Spano and for reaching out!

I think I understand what you're suggesting, but this bumps up against my ignorance of how to package up Flask applications. In my (limited) experience, deploying a Flask application has involved checking out the application code on a host and configuring it to run with some WSGI-capable server.

I'm not familiar with the process of installing the code for a whole Flask app as a package and then configuring it to be run, so I am not sure how to proceed.

Pull requests are most welcome! I'm also open to links to docs / blog posts on where to learn more about this!

Thanks again.

**Comment by vikanezrimaya** [comment]
A Flask application can be installed into Python path and then launched from it with a WSGI-capable server, like uwsgi. In this case the launching goes like "pyindieblog.renderer:get_app()" or "flaskr:app" instead of specifying a file.

That's how I manage my Python applications, anyway. uWSGI has a Python installation configured that has my applications installed already - so uwsgi just mounts applications that are packaged and installed. Configuration is applied via environment variables and config files.

An example can be seen at https://git.fireburn.ru/pyindieblog.git/plain/configuration.nix (I'm giving you a plain-text link since my syntax highlighter is broken).

**Comment by vikanezrimaya** [comment]
Oh, by the way, forgot to mention - having a setup.py doesn't prevent you from running your code from a Git checkout! 

I'll probably file a PR once I finish some of my work...
